title = "gitleaks config"

[[rules]]
    description = "General leak in dockerfile"
    regex = '''(^ENV)(.*)(DATABASE|USER|PASSWORD)(\ )(.?$|[^\$].*)$'''
    tags = ["password", "secret", "dockerfile"]
