name: gitleaks

on: push

jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        id: gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          GITLEAKS_CONFIG: gitleaks.toml

      - name: Upload SARIF file
        if: failure() && steps.gitleaks.outcome != 'success'
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: *.sarif
          category: gitleaks
